changesetBaseRefs:
  - main
  - publish
  - origin/main
  - upstream/main

enableTelemetry: false
nodeLinker: node-modules

npmAuthToken: "${NPM_AUTH_TOKEN:-}"

packageExtensions:
  debug@*:
    peerDependenciesMeta:
      supports-color:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
