afterInstall: yarn postinstall

changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmAuthToken: '${NPM_AUTH_TOKEN:-}'

packageExtensions:
  debug@*:
    peerDependenciesMeta:
      supports-color:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.6.0/bundles/@yarnpkg/plugin-after-install.js'

yarnPath: .yarn/releases/yarn-4.1.1.cjs
