changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

enableTelemetry: false

nodeLinker: node-modules

npmAuthToken: '${NPM_AUTH_TOKEN:-}'

packageExtensions:
  debug@*:
    peerDependenciesMeta:
      supports-color:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.6.0/bundles/@yarnpkg/plugin-after-install.js'

yarnPath: .yarn/releases/yarn-3.6.0.cjs

afterInstall: yarn postinstall
