/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace IDemoVerifier {
  export type IdentityProofInfoStruct = {
    senderAddr: string;
    isProved: boolean;
  };

  export type IdentityProofInfoStructOutput = [string, boolean] & {
    senderAddr: string;
    isProved: boolean;
  };
}

export declare namespace ILightweightState {
  export type StatesMerkleDataStruct = {
    issuerId: BigNumberish;
    issuerState: BigNumberish;
    createdAtTimestamp: BigNumberish;
    merkleProof: BytesLike[];
  };

  export type StatesMerkleDataStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    string[]
  ] & {
    issuerId: BigNumber;
    issuerState: BigNumber;
    createdAtTimestamp: BigNumber;
    merkleProof: string[];
  };
}

export interface DemoVerifierInterface extends utils.Interface {
  functions: {
    "__DemoVerifier_init(address)": FunctionFragment;
    "addressToIdentityId(address)": FunctionFragment;
    "getAllowedIssuers(uint256)": FunctionFragment;
    "getIdentityProofInfo(uint256)": FunctionFragment;
    "isAllowedIssuer(uint256,uint256)": FunctionFragment;
    "isIdentityProved(address)": FunctionFragment;
    "isIdentityProved(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "proveIdentity((uint256,uint256,uint256,bytes32[]),uint256[],uint256[2],uint256[2][2],uint256[2])": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setZKPQueriesStorage(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateAllowedIssuers(uint256,uint256[],bool)": FunctionFragment;
    "zkpQueriesStorage()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "__DemoVerifier_init"
      | "addressToIdentityId"
      | "getAllowedIssuers"
      | "getIdentityProofInfo"
      | "isAllowedIssuer"
      | "isIdentityProved(address)"
      | "isIdentityProved(uint256)"
      | "owner"
      | "proveIdentity"
      | "renounceOwnership"
      | "setZKPQueriesStorage"
      | "transferOwnership"
      | "updateAllowedIssuers"
      | "zkpQueriesStorage"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "__DemoVerifier_init",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addressToIdentityId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowedIssuers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIdentityProofInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowedIssuer",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isIdentityProved(address)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isIdentityProved(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proveIdentity",
    values: [
      ILightweightState.StatesMerkleDataStruct,
      BigNumberish[],
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setZKPQueriesStorage",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAllowedIssuers",
    values: [BigNumberish, BigNumberish[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "zkpQueriesStorage",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "__DemoVerifier_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressToIdentityId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowedIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIdentityProofInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAllowedIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isIdentityProved(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isIdentityProved(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proveIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setZKPQueriesStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAllowedIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zkpQueriesStorage",
    data: BytesLike
  ): Result;

  events: {
    "IdentityProved(uint256,address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "IdentityProved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface IdentityProvedEventObject {
  identityId: BigNumber;
  senderAddr: string;
}
export type IdentityProvedEvent = TypedEvent<
  [BigNumber, string],
  IdentityProvedEventObject
>;

export type IdentityProvedEventFilter = TypedEventFilter<IdentityProvedEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface DemoVerifier extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DemoVerifierInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    __DemoVerifier_init(
      zkpQueriesStorage_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    addressToIdentityId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAllowedIssuers(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getIdentityProofInfo(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IDemoVerifier.IdentityProofInfoStructOutput]>;

    isAllowedIssuer(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isIdentityProved(address)"(
      userAddr_: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isIdentityProved(uint256)"(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    proveIdentity(
      statesMerkleData_: ILightweightState.StatesMerkleDataStruct,
      inputs_: BigNumberish[],
      a_: [BigNumberish, BigNumberish],
      b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c_: [BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setZKPQueriesStorage(
      newZKPQueriesStorage_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateAllowedIssuers(
      schema_: BigNumberish,
      issuerIds_: BigNumberish[],
      isAdding_: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    zkpQueriesStorage(overrides?: CallOverrides): Promise<[string]>;
  };

  __DemoVerifier_init(
    zkpQueriesStorage_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  addressToIdentityId(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAllowedIssuers(
    schema_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getIdentityProofInfo(
    identityId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IDemoVerifier.IdentityProofInfoStructOutput>;

  isAllowedIssuer(
    schema_: BigNumberish,
    issuerId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isIdentityProved(address)"(
    userAddr_: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isIdentityProved(uint256)"(
    identityId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  proveIdentity(
    statesMerkleData_: ILightweightState.StatesMerkleDataStruct,
    inputs_: BigNumberish[],
    a_: [BigNumberish, BigNumberish],
    b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
    c_: [BigNumberish, BigNumberish],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setZKPQueriesStorage(
    newZKPQueriesStorage_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateAllowedIssuers(
    schema_: BigNumberish,
    issuerIds_: BigNumberish[],
    isAdding_: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  zkpQueriesStorage(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    __DemoVerifier_init(
      zkpQueriesStorage_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addressToIdentityId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllowedIssuers(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getIdentityProofInfo(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IDemoVerifier.IdentityProofInfoStructOutput>;

    isAllowedIssuer(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isIdentityProved(address)"(
      userAddr_: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isIdentityProved(uint256)"(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    proveIdentity(
      statesMerkleData_: ILightweightState.StatesMerkleDataStruct,
      inputs_: BigNumberish[],
      a_: [BigNumberish, BigNumberish],
      b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c_: [BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setZKPQueriesStorage(
      newZKPQueriesStorage_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateAllowedIssuers(
      schema_: BigNumberish,
      issuerIds_: BigNumberish[],
      isAdding_: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    zkpQueriesStorage(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "IdentityProved(uint256,address)"(
      identityId?: BigNumberish | null,
      senderAddr?: null
    ): IdentityProvedEventFilter;
    IdentityProved(
      identityId?: BigNumberish | null,
      senderAddr?: null
    ): IdentityProvedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    __DemoVerifier_init(
      zkpQueriesStorage_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    addressToIdentityId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllowedIssuers(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIdentityProofInfo(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAllowedIssuer(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isIdentityProved(address)"(
      userAddr_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isIdentityProved(uint256)"(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    proveIdentity(
      statesMerkleData_: ILightweightState.StatesMerkleDataStruct,
      inputs_: BigNumberish[],
      a_: [BigNumberish, BigNumberish],
      b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c_: [BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setZKPQueriesStorage(
      newZKPQueriesStorage_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateAllowedIssuers(
      schema_: BigNumberish,
      issuerIds_: BigNumberish[],
      isAdding_: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    zkpQueriesStorage(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    __DemoVerifier_init(
      zkpQueriesStorage_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addressToIdentityId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllowedIssuers(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIdentityProofInfo(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAllowedIssuer(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isIdentityProved(address)"(
      userAddr_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isIdentityProved(uint256)"(
      identityId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proveIdentity(
      statesMerkleData_: ILightweightState.StatesMerkleDataStruct,
      inputs_: BigNumberish[],
      a_: [BigNumberish, BigNumberish],
      b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c_: [BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setZKPQueriesStorage(
      newZKPQueriesStorage_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateAllowedIssuers(
      schema_: BigNumberish,
      issuerIds_: BigNumberish[],
      isAdding_: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    zkpQueriesStorage(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
