/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace StateV2 {
  export type SchemaInfoDetailedStruct = {
    lastSerialNumber: BigNumberish;
    claimsCount: BigNumberish;
    revokedClaims: BigNumberish[];
  };

  export type SchemaInfoDetailedStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber[]
  ] & {
    lastSerialNumber: BigNumber;
    claimsCount: BigNumber;
    revokedClaims: BigNumber[];
  };
}

export declare namespace IState {
  export type GistProofStruct = {
    root: BigNumberish;
    existence: boolean;
    siblings: BigNumberish[];
    index: BigNumberish;
    value: BigNumberish;
    auxExistence: boolean;
    auxIndex: BigNumberish;
    auxValue: BigNumberish;
  };

  export type GistProofStructOutput = [
    BigNumber,
    boolean,
    BigNumber[],
    BigNumber,
    BigNumber,
    boolean,
    BigNumber,
    BigNumber
  ] & {
    root: BigNumber;
    existence: boolean;
    siblings: BigNumber[];
    index: BigNumber;
    value: BigNumber;
    auxExistence: boolean;
    auxIndex: BigNumber;
    auxValue: BigNumber;
  };

  export type GistRootInfoStruct = {
    root: BigNumberish;
    replacedByRoot: BigNumberish;
    createdAtTimestamp: BigNumberish;
    replacedAtTimestamp: BigNumberish;
    createdAtBlock: BigNumberish;
    replacedAtBlock: BigNumberish;
  };

  export type GistRootInfoStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    root: BigNumber;
    replacedByRoot: BigNumber;
    createdAtTimestamp: BigNumber;
    replacedAtTimestamp: BigNumber;
    createdAtBlock: BigNumber;
    replacedAtBlock: BigNumber;
  };

  export type StateInfoStruct = {
    id: BigNumberish;
    state: BigNumberish;
    replacedByState: BigNumberish;
    createdAtTimestamp: BigNumberish;
    replacedAtTimestamp: BigNumberish;
    createdAtBlock: BigNumberish;
    replacedAtBlock: BigNumberish;
  };

  export type StateInfoStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    id: BigNumber;
    state: BigNumber;
    replacedByState: BigNumber;
    createdAtTimestamp: BigNumber;
    replacedAtTimestamp: BigNumber;
    createdAtBlock: BigNumber;
    replacedAtBlock: BigNumber;
  };
}

export interface StateV2Interface extends utils.Interface {
  functions: {
    "MAX_CLAIM_COMMIT_COUNT()": FunctionFragment;
    "__StateV2_init(address,address,uint256[],uint256[][])": FunctionFragment;
    "acceptOwnership()": FunctionFragment;
    "getAllowedIssuers(uint256)": FunctionFragment;
    "getDetailedSchemaInfo(uint256,uint256)": FunctionFragment;
    "getGISTProof(uint256)": FunctionFragment;
    "getGISTProofByBlock(uint256,uint256)": FunctionFragment;
    "getGISTProofByRoot(uint256,uint256)": FunctionFragment;
    "getGISTProofByTime(uint256,uint256)": FunctionFragment;
    "getGISTRoot()": FunctionFragment;
    "getGISTRootHistory(uint256,uint256)": FunctionFragment;
    "getGISTRootHistoryLength()": FunctionFragment;
    "getGISTRootInfo(uint256)": FunctionFragment;
    "getGISTRootInfoByBlock(uint256)": FunctionFragment;
    "getGISTRootInfoByTime(uint256)": FunctionFragment;
    "getNumberOfClaims(uint256[],uint256)": FunctionFragment;
    "getNumberOfClaims(uint256)": FunctionFragment;
    "getStateInfoById(uint256)": FunctionFragment;
    "getStateInfoByIdAndState(uint256,uint256)": FunctionFragment;
    "getStateInfoHistoryById(uint256,uint256,uint256)": FunctionFragment;
    "getStateInfoHistoryLengthById(uint256)": FunctionFragment;
    "getStateVerifier()": FunctionFragment;
    "getStateVerifierWithCommit()": FunctionFragment;
    "idExists(uint256)": FunctionFragment;
    "isAllowedIssuer(uint256,uint256)": FunctionFragment;
    "isClaimRevoked(uint256,uint256,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "pendingOwner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setVerifier(address,address)": FunctionFragment;
    "stateExists(uint256,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transitState(uint256[],uint256[2],uint256[2][2],uint256[2])": FunctionFragment;
    "transitStateWithCommit(uint256[],uint256[2],uint256[2][2],uint256[2])": FunctionFragment;
    "updateAllowedIssuers(uint256[],uint256[][],bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MAX_CLAIM_COMMIT_COUNT"
      | "__StateV2_init"
      | "acceptOwnership"
      | "getAllowedIssuers"
      | "getDetailedSchemaInfo"
      | "getGISTProof"
      | "getGISTProofByBlock"
      | "getGISTProofByRoot"
      | "getGISTProofByTime"
      | "getGISTRoot"
      | "getGISTRootHistory"
      | "getGISTRootHistoryLength"
      | "getGISTRootInfo"
      | "getGISTRootInfoByBlock"
      | "getGISTRootInfoByTime"
      | "getNumberOfClaims(uint256[],uint256)"
      | "getNumberOfClaims(uint256)"
      | "getStateInfoById"
      | "getStateInfoByIdAndState"
      | "getStateInfoHistoryById"
      | "getStateInfoHistoryLengthById"
      | "getStateVerifier"
      | "getStateVerifierWithCommit"
      | "idExists"
      | "isAllowedIssuer"
      | "isClaimRevoked"
      | "owner"
      | "pendingOwner"
      | "renounceOwnership"
      | "setVerifier"
      | "stateExists"
      | "transferOwnership"
      | "transitState"
      | "transitStateWithCommit"
      | "updateAllowedIssuers"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MAX_CLAIM_COMMIT_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "__StateV2_init",
    values: [string, string, BigNumberish[], BigNumberish[][]]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowedIssuers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDetailedSchemaInfo",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGISTProof",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGISTProofByBlock",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGISTProofByRoot",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGISTProofByTime",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGISTRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGISTRootHistory",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGISTRootHistoryLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGISTRootInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGISTRootInfoByBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGISTRootInfoByTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNumberOfClaims(uint256[],uint256)",
    values: [BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNumberOfClaims(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateInfoById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateInfoByIdAndState",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateInfoHistoryById",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateInfoHistoryLengthById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStateVerifierWithCommit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "idExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowedIssuer",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isClaimRevoked",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifier",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "stateExists",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transitState",
    values: [
      BigNumberish[],
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transitStateWithCommit",
    values: [
      BigNumberish[],
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAllowedIssuers",
    values: [BigNumberish[], BigNumberish[][], boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_CLAIM_COMMIT_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "__StateV2_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowedIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDetailedSchemaInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGISTProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGISTProofByBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGISTProofByRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGISTProofByTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGISTRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGISTRootHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGISTRootHistoryLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGISTRootInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGISTRootInfoByBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGISTRootInfoByTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumberOfClaims(uint256[],uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumberOfClaims(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStateInfoById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStateInfoByIdAndState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStateInfoHistoryById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStateInfoHistoryLengthById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStateVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStateVerifierWithCommit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "idExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAllowedIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isClaimRevoked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stateExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transitState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transitStateWithCommit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAllowedIssuers",
    data: BytesLike
  ): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferStarted(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "StateUpdated(uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StateUpdated"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferStartedEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferStartedEvent = TypedEvent<
  [string, string],
  OwnershipTransferStartedEventObject
>;

export type OwnershipTransferStartedEventFilter =
  TypedEventFilter<OwnershipTransferStartedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface StateUpdatedEventObject {
  id: BigNumber;
  blockN: BigNumber;
  timestamp: BigNumber;
  state: BigNumber;
}
export type StateUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber],
  StateUpdatedEventObject
>;

export type StateUpdatedEventFilter = TypedEventFilter<StateUpdatedEvent>;

export interface StateV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StateV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAX_CLAIM_COMMIT_COUNT(overrides?: CallOverrides): Promise<[BigNumber]>;

    __StateV2_init(
      stateVerifier_: string,
      stateVerifierWithCommit_: string,
      schemas_: BigNumberish[],
      issuersId_: BigNumberish[][],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    acceptOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getAllowedIssuers(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getDetailedSchemaInfo(
      issuerId_: BigNumberish,
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[StateV2.SchemaInfoDetailedStructOutput]>;

    getGISTProof(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IState.GistProofStructOutput]>;

    getGISTProofByBlock(
      id: BigNumberish,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IState.GistProofStructOutput]>;

    getGISTProofByRoot(
      id: BigNumberish,
      root: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IState.GistProofStructOutput]>;

    getGISTProofByTime(
      id: BigNumberish,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IState.GistProofStructOutput]>;

    getGISTRoot(overrides?: CallOverrides): Promise<[BigNumber]>;

    getGISTRootHistory(
      start: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IState.GistRootInfoStructOutput[]]>;

    getGISTRootHistoryLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    getGISTRootInfo(
      root: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IState.GistRootInfoStructOutput]>;

    getGISTRootInfoByBlock(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IState.GistRootInfoStructOutput]>;

    getGISTRootInfoByTime(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IState.GistRootInfoStructOutput]>;

    "getNumberOfClaims(uint256[],uint256)"(
      issuersId_: BigNumberish[],
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getNumberOfClaims(uint256)"(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getStateInfoById(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IState.StateInfoStructOutput]>;

    getStateInfoByIdAndState(
      id: BigNumberish,
      state: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IState.StateInfoStructOutput]>;

    getStateInfoHistoryById(
      id: BigNumberish,
      startIndex: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IState.StateInfoStructOutput[]]>;

    getStateInfoHistoryLengthById(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getStateVerifier(overrides?: CallOverrides): Promise<[string]>;

    getStateVerifierWithCommit(overrides?: CallOverrides): Promise<[string]>;

    idExists(id: BigNumberish, overrides?: CallOverrides): Promise<[boolean]>;

    isAllowedIssuer(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isClaimRevoked(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      serialNumber_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pendingOwner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setVerifier(
      stateVerifier_: string,
      stateVerifierWithCommit_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    stateExists(
      id: BigNumberish,
      state: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transitState(
      inputs_: BigNumberish[],
      a_: [BigNumberish, BigNumberish],
      b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c_: [BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transitStateWithCommit(
      inputs_: BigNumberish[],
      a_: [BigNumberish, BigNumberish],
      b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c_: [BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateAllowedIssuers(
      schemas_: BigNumberish[],
      issuersId_: BigNumberish[][],
      isAdding_: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  MAX_CLAIM_COMMIT_COUNT(overrides?: CallOverrides): Promise<BigNumber>;

  __StateV2_init(
    stateVerifier_: string,
    stateVerifierWithCommit_: string,
    schemas_: BigNumberish[],
    issuersId_: BigNumberish[][],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  acceptOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getAllowedIssuers(
    schema_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getDetailedSchemaInfo(
    issuerId_: BigNumberish,
    schema_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<StateV2.SchemaInfoDetailedStructOutput>;

  getGISTProof(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IState.GistProofStructOutput>;

  getGISTProofByBlock(
    id: BigNumberish,
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IState.GistProofStructOutput>;

  getGISTProofByRoot(
    id: BigNumberish,
    root: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IState.GistProofStructOutput>;

  getGISTProofByTime(
    id: BigNumberish,
    timestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IState.GistProofStructOutput>;

  getGISTRoot(overrides?: CallOverrides): Promise<BigNumber>;

  getGISTRootHistory(
    start: BigNumberish,
    length: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IState.GistRootInfoStructOutput[]>;

  getGISTRootHistoryLength(overrides?: CallOverrides): Promise<BigNumber>;

  getGISTRootInfo(
    root: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IState.GistRootInfoStructOutput>;

  getGISTRootInfoByBlock(
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IState.GistRootInfoStructOutput>;

  getGISTRootInfoByTime(
    timestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IState.GistRootInfoStructOutput>;

  "getNumberOfClaims(uint256[],uint256)"(
    issuersId_: BigNumberish[],
    schema_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getNumberOfClaims(uint256)"(
    schema_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getStateInfoById(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IState.StateInfoStructOutput>;

  getStateInfoByIdAndState(
    id: BigNumberish,
    state: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IState.StateInfoStructOutput>;

  getStateInfoHistoryById(
    id: BigNumberish,
    startIndex: BigNumberish,
    length: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IState.StateInfoStructOutput[]>;

  getStateInfoHistoryLengthById(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getStateVerifier(overrides?: CallOverrides): Promise<string>;

  getStateVerifierWithCommit(overrides?: CallOverrides): Promise<string>;

  idExists(id: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  isAllowedIssuer(
    schema_: BigNumberish,
    issuerId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isClaimRevoked(
    schema_: BigNumberish,
    issuerId_: BigNumberish,
    serialNumber_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  pendingOwner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setVerifier(
    stateVerifier_: string,
    stateVerifierWithCommit_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  stateExists(
    id: BigNumberish,
    state: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transitState(
    inputs_: BigNumberish[],
    a_: [BigNumberish, BigNumberish],
    b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
    c_: [BigNumberish, BigNumberish],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transitStateWithCommit(
    inputs_: BigNumberish[],
    a_: [BigNumberish, BigNumberish],
    b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
    c_: [BigNumberish, BigNumberish],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateAllowedIssuers(
    schemas_: BigNumberish[],
    issuersId_: BigNumberish[][],
    isAdding_: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    MAX_CLAIM_COMMIT_COUNT(overrides?: CallOverrides): Promise<BigNumber>;

    __StateV2_init(
      stateVerifier_: string,
      stateVerifierWithCommit_: string,
      schemas_: BigNumberish[],
      issuersId_: BigNumberish[][],
      overrides?: CallOverrides
    ): Promise<void>;

    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    getAllowedIssuers(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getDetailedSchemaInfo(
      issuerId_: BigNumberish,
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<StateV2.SchemaInfoDetailedStructOutput>;

    getGISTProof(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IState.GistProofStructOutput>;

    getGISTProofByBlock(
      id: BigNumberish,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IState.GistProofStructOutput>;

    getGISTProofByRoot(
      id: BigNumberish,
      root: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IState.GistProofStructOutput>;

    getGISTProofByTime(
      id: BigNumberish,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IState.GistProofStructOutput>;

    getGISTRoot(overrides?: CallOverrides): Promise<BigNumber>;

    getGISTRootHistory(
      start: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IState.GistRootInfoStructOutput[]>;

    getGISTRootHistoryLength(overrides?: CallOverrides): Promise<BigNumber>;

    getGISTRootInfo(
      root: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IState.GistRootInfoStructOutput>;

    getGISTRootInfoByBlock(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IState.GistRootInfoStructOutput>;

    getGISTRootInfoByTime(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IState.GistRootInfoStructOutput>;

    "getNumberOfClaims(uint256[],uint256)"(
      issuersId_: BigNumberish[],
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNumberOfClaims(uint256)"(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStateInfoById(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IState.StateInfoStructOutput>;

    getStateInfoByIdAndState(
      id: BigNumberish,
      state: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IState.StateInfoStructOutput>;

    getStateInfoHistoryById(
      id: BigNumberish,
      startIndex: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IState.StateInfoStructOutput[]>;

    getStateInfoHistoryLengthById(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStateVerifier(overrides?: CallOverrides): Promise<string>;

    getStateVerifierWithCommit(overrides?: CallOverrides): Promise<string>;

    idExists(id: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    isAllowedIssuer(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isClaimRevoked(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      serialNumber_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    pendingOwner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setVerifier(
      stateVerifier_: string,
      stateVerifierWithCommit_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    stateExists(
      id: BigNumberish,
      state: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transitState(
      inputs_: BigNumberish[],
      a_: [BigNumberish, BigNumberish],
      b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c_: [BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<void>;

    transitStateWithCommit(
      inputs_: BigNumberish[],
      a_: [BigNumberish, BigNumberish],
      b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c_: [BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<void>;

    updateAllowedIssuers(
      schemas_: BigNumberish[],
      issuersId_: BigNumberish[][],
      isAdding_: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferStarted(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferStartedEventFilter;
    OwnershipTransferStarted(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferStartedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "StateUpdated(uint256,uint256,uint256,uint256)"(
      id?: null,
      blockN?: null,
      timestamp?: null,
      state?: null
    ): StateUpdatedEventFilter;
    StateUpdated(
      id?: null,
      blockN?: null,
      timestamp?: null,
      state?: null
    ): StateUpdatedEventFilter;
  };

  estimateGas: {
    MAX_CLAIM_COMMIT_COUNT(overrides?: CallOverrides): Promise<BigNumber>;

    __StateV2_init(
      stateVerifier_: string,
      stateVerifierWithCommit_: string,
      schemas_: BigNumberish[],
      issuersId_: BigNumberish[][],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    acceptOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getAllowedIssuers(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDetailedSchemaInfo(
      issuerId_: BigNumberish,
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGISTProof(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGISTProofByBlock(
      id: BigNumberish,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGISTProofByRoot(
      id: BigNumberish,
      root: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGISTProofByTime(
      id: BigNumberish,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGISTRoot(overrides?: CallOverrides): Promise<BigNumber>;

    getGISTRootHistory(
      start: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGISTRootHistoryLength(overrides?: CallOverrides): Promise<BigNumber>;

    getGISTRootInfo(
      root: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGISTRootInfoByBlock(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGISTRootInfoByTime(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNumberOfClaims(uint256[],uint256)"(
      issuersId_: BigNumberish[],
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNumberOfClaims(uint256)"(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStateInfoById(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStateInfoByIdAndState(
      id: BigNumberish,
      state: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStateInfoHistoryById(
      id: BigNumberish,
      startIndex: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStateInfoHistoryLengthById(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStateVerifier(overrides?: CallOverrides): Promise<BigNumber>;

    getStateVerifierWithCommit(overrides?: CallOverrides): Promise<BigNumber>;

    idExists(id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    isAllowedIssuer(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isClaimRevoked(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      serialNumber_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pendingOwner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setVerifier(
      stateVerifier_: string,
      stateVerifierWithCommit_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    stateExists(
      id: BigNumberish,
      state: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transitState(
      inputs_: BigNumberish[],
      a_: [BigNumberish, BigNumberish],
      b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c_: [BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transitStateWithCommit(
      inputs_: BigNumberish[],
      a_: [BigNumberish, BigNumberish],
      b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c_: [BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateAllowedIssuers(
      schemas_: BigNumberish[],
      issuersId_: BigNumberish[][],
      isAdding_: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_CLAIM_COMMIT_COUNT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    __StateV2_init(
      stateVerifier_: string,
      stateVerifierWithCommit_: string,
      schemas_: BigNumberish[],
      issuersId_: BigNumberish[][],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    acceptOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getAllowedIssuers(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDetailedSchemaInfo(
      issuerId_: BigNumberish,
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGISTProof(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGISTProofByBlock(
      id: BigNumberish,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGISTProofByRoot(
      id: BigNumberish,
      root: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGISTProofByTime(
      id: BigNumberish,
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGISTRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getGISTRootHistory(
      start: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGISTRootHistoryLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGISTRootInfo(
      root: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGISTRootInfoByBlock(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGISTRootInfoByTime(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getNumberOfClaims(uint256[],uint256)"(
      issuersId_: BigNumberish[],
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getNumberOfClaims(uint256)"(
      schema_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStateInfoById(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStateInfoByIdAndState(
      id: BigNumberish,
      state: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStateInfoHistoryById(
      id: BigNumberish,
      startIndex: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStateInfoHistoryLengthById(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStateVerifier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStateVerifierWithCommit(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    idExists(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAllowedIssuer(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isClaimRevoked(
      schema_: BigNumberish,
      issuerId_: BigNumberish,
      serialNumber_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setVerifier(
      stateVerifier_: string,
      stateVerifierWithCommit_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    stateExists(
      id: BigNumberish,
      state: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transitState(
      inputs_: BigNumberish[],
      a_: [BigNumberish, BigNumberish],
      b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c_: [BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transitStateWithCommit(
      inputs_: BigNumberish[],
      a_: [BigNumberish, BigNumberish],
      b_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c_: [BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateAllowedIssuers(
      schemas_: BigNumberish[],
      issuersId_: BigNumberish[][],
      isAdding_: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
