export * from './CreateIdentity';
export * from './SaveCredentials';
export * from './RemoveCredentials';
export * from './CheckCredentialExistence';
export * from './CreateProof';
export * from './CheckStateContractSync';
export * from './GetCredentials';
export * from './ExportIdentity';
export * from './GetIdentity';
