name: Lint and test

on: [pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}
      - name: Lint and test
        run: |
          yarn install
          yarn build
          yarn lint
          yarn test
